nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:3000']
        allow_headers: ['Authorization', 'Content-Type']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE','PATCH', 'OPTIONS']
        expose_headers: []
        max_age: 3600
    paths:
        '^/': ~
